#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter=""
dry=false

while [[ $# > 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry=true
    else
        # TODO: add to list?
        filter="$1"
    fi
    shift
done

log() {
    if [ "$dry" = true ]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute $@"
    if [ "$dry" = true ]; then
        return
    fi
    "$@"
}

log "$script_dir -- $filter"

cd $script_dir
scripts=$(find ./runs -maxdepth 1 -mindepth 1 -executable -type f)

for script in $scripts; do
    if echo "$script" | grep -qv "$filter"; then
        log "filtering: $filter -- $script"
        continue
    fi

    log "running script: $script"
    execute ./$script
done

